services:
  database:
    image: postgres:14.1
    environment:
      - POSTGRES_DB=oauth-login-evaluation
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    environment:
      - TZ=Asia/Taipei
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_HOSTNAME=localhost
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      # - KC_HTTPS_CERTIFICATE_KEY_FILE=/certs/privkey.pem
      # - KC_HTTPS_CERTIFICATE_FILE=/certs/fullchain.pem
      # - KC_HTTPS_PORT=8443
    ports:
      - 8080:8080
      - 8443:8443
    command:
      start-dev
      # start
    volumes:
      - ./certs:/certs
volumes:
  db-data:
    driver: local
